const data = {
  products: [
    {
      name: 'Samsung Galaxy S10+',
      slug: 'Samsung-Galaxy-S10+',
      category: 'Mobile',
      image: '/images/2.jpg',
      price: 400,
      countInStock: 10,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality Mobile',
    },
    {
      name: 'Apple Iphone 12 Pro',
      slug: 'Apple-Iphone-12-Pro',
      category: 'Mobile',
      image: '/images/4.jpg',
      price: 400,
      countInStock: 0,
      brand: 'Iphone',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality Mobile',
    },
    {
      name: 'Dell Alienware 10 Gen',
      slug: 'Dell-Alienware-10-Gen',
      category: 'Laptop',
      image: '/images/3.jpg',
      price: 400,
      countInStock: 10,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality Laptop',
    },
    {
      name: 'Apple Mac Book',
      slug: 'Apple-Mac-Book',
      category: 'Laptop',
      image: '/images/1.jpg',
      price: 400,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality Laptop',
    },
  ],
};

export default data;
